name: app
version: 0.0.3+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.7
  permission_handler: ^8.1.6
  provider: ^6.0.0
  shared_preferences: ^2.0.9
  sqflite: ^2.0.0+4
  logger: ^1.1.0
  firebase_core: ^1.10.0
  get: ^4.5.1
  firebase_auth: ^3.2.0
  google_sign_in: ^5.2.1
  image_picker: ^0.8.4+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/